### ISSUE TITLE
KDE also has a kbackup

### ISSUE THREAD

**Issue by kseistrup** [thekashifmalik/rincr#2]
The name `kbackup` is also used by a backup utility for KDE:

* https://apps.kde.org/en-gb/kbackup/
* https://archlinux.org/packages/extra/x86_64/kbackup/

While there are no rules that forbid name collisions, this _will_ create problems for packagers who decide to package your `kbackup` for a distro that also carries KDE's `kbackup`. E.g.: since the latter is already in ArchLinux extra, a package with your `kbackup` will need another name.

**Comment by thekashifmalik** [comment]
That is unfortunate. Will have to consider other names before v1. Will think about this more.

**Comment by kseistrup** [comment]
It's not an easy one. Names like `ksnapshot`, `ksync` and `krsync` are all “taken” (assuming you wish to keep the `k`).

Many `k`-names are taken because of KDE.

Many `q`-names are taken because of Qt or the word “quick”, e.g. `qbackup`.

**Comment by thekashifmalik** [comment]
That's fine; I'm not married to the `k`. If anything, I'd like to find a shorter name.

**Comment by kseistrup** [comment]
Shorter? How about `sama` (“backup” in [toki pona](https://tokipona.org/ "The language of good")). :wink:

**Comment by thekashifmalik** [comment]
The criteria I'm using is:

- It has to be short enough to type comfortably.
- It has to have a domain available.
- I have to feel an affinity for it.

Admittedly, that last point is a little fuzzy.

> Shorter? How about `sama` (“backup” in [toki pona](https://tokipona.org/)). 😉

I'm not drawn to it and unfortunately there are no common domains available. Would like to see if there is something technical that could make sense, similar to `rsync`,  `rclone`, `rsnapshot` or  `rdiff-backup`.

**Comment by thekashifmalik** [comment]
Based on the criteria, I'm leaning towards `rincr`.

It makes the migration from `rsync`-based mirrored backups to `rincr`-based incremental backups look natural:

```bash
# mirrored backup
rsync myserver:~/mydata /backups

# incremental backup
rincr myserver:~/mydata /backups
```

**Comment by thekashifmalik** [comment]
I updated the name. Note that running `rincr` after upgrading will delete pre-existing historical backups. I think this is fine given this software is not yet at v1.
